language: java
jdk: oraclejdk8
services:
  - postgresql
before_script:
  - psql -c 'CREATE DATABASE aula;' -U postgres
  - psql -U postgres -d aula -a -f Scripts/Database.txt
# whitelist
branches:
  only:
    - 1.0.0
